#!/usr/bin/env python3
"""Quizzes A/B/C for Module F L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-f",
    "level": "l3",
    "year": "y1",
    "module": "F",
    "title": "Staying Safe at College",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-f-A01", "type": "scored",
     "prompt": "Which PROUD value is this module grounded in?",
     "options": ["Seek Opportunity", "Show Respect", "Encourage Unity", "Be Proud"],
     "answerIndex": 2,
     "explanation": "Encourage Unity - creating an environment where it's normal to look out for peers and report concern."},
    {"id": "l3y1-f-A02", "type": "scored",
     "prompt": "According to the deck, on placement or on a shoot, who holds part of the safeguarding duty around consent, conduct, and what you record?",
     "options": ["Only the placement provider",
                 "Only the college safeguarding team",
                 "You do",
                 "Only the unit lecturer"],
     "answerIndex": 2,
     "explanation": "On placement and on a shoot you hold part of this duty yourself."},
    {"id": "l3y1-f-A03", "type": "scored",
     "prompt": "How does the deck define extremism?",
     "options": ["Holding strong opinions",
                 "Vocal or active opposition to fundamental British values, or calls for violence against others",
                 "Asking difficult questions",
                 "Joining a political party"],
     "answerIndex": 1,
     "explanation": "Extremism is vocal or active opposition to fundamental British values, or calls for violence against others."},
    {"id": "l3y1-f-A04", "type": "scored",
     "prompt": "Where does the deck say the greatest local risk of radicalisation comes from?",
     "options": ["Places of worship",
                 "Classrooms",
                 "The online space - particularly misogynistic and extreme right-wing content and lone-actor narratives",
                 "Student unions"],
     "answerIndex": 2,
     "explanation": "Locally, the greatest risk of radicalisation comes from the online space."},
    {"id": "l3y1-f-A05", "type": "scored",
     "prompt": "Which of these is the deck's reframe of grooming?",
     "options": ["It's only a risk on dating apps",
                 "Adults who build 'relationships' online with young people for harmful purposes; county lines recruitment works the same way - it usually arrives as a DM offering paid portfolio, modelling or editing work",
                 "It's only a risk for under-16s",
                 "It only happens in person"],
     "answerIndex": 1,
     "explanation": "Grooming and exploitation: adults who build 'relationships' online with young people for harmful purposes; county lines recruitment works the same way."},
    {"id": "l3y1-f-A06", "type": "insert",
     "prompt": "Fill in the blank: sharing intimate images without consent is a criminal offence; receiving or sharing ____ counts.",
     "template": "Sharing intimate images without consent is a criminal offence; receiving or sharing ____ counts.",
     "options": ["sometimes", "both", "neither", "only if public"],
     "answerIndex": 1,
     "explanation": "Receiving or sharing both count - and this includes AI-generated images."},
    {"id": "l3y1-f-A07", "type": "scored",
     "prompt": "What's the deck's headline about using AI in assessments?",
     "options": ["AI tools are always wrong",
                 "Use AI to support, not replace - and verify what AI tells you because AI tools fabricate facts, invent sources, and present errors confidently",
                 "Submit whatever AI produces",
                 "Never use AI"],
     "answerIndex": 1,
     "explanation": "Use AI to support, not replace; verify what AI tells you - AI tools fabricate facts."},
    {"id": "l3y1-f-A08", "type": "scored",
     "prompt": "What does the deck say staff cannot promise when a safeguarding concern is raised?",
     "options": ["Same-day logging",
                 "Secrecy",
                 "A referral to external agencies",
                 "ProMonitor access"],
     "answerIndex": 1,
     "explanation": "Staff will not gossip or share unnecessarily, but they cannot promise secrecy."},
    {"id": "l3y1-f-A09", "type": "scored",
     "prompt": "What does the deck say is the right framing for telling someone you're worried about a friend?",
     "options": ["It's a betrayal",
                 "It's the right thing to do - it's not a betrayal",
                 "It must wait until you're sure",
                 "Only your tutor can do it"],
     "answerIndex": 1,
     "explanation": "Acting on concern for a friend is the right thing. It is not a betrayal."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-f-B01", "type": "scored",
     "prompt": "What does the deck say about college being different from school?",
     "options": ["More monitoring and less autonomy",
                 "More autonomy and less monitoring - but staff are paying attention; you can also self-refer to the Safeguarding Team",
                 "Same level of monitoring",
                 "Students are tracked more closely"],
     "answerIndex": 1,
     "explanation": "More autonomy, less monitoring - and you can self-refer."},
    {"id": "l3y1-f-B02", "type": "multi",
     "prompt": "Which of these are vulnerability factors for radicalisation listed in the deck? Select all that apply.",
     "options": ["Feeling isolated, excluded, or like you don't belong",
                 "Searching for identity or a sense of purpose",
                 "Grievances (real or perceived) that feel unaddressed",
                 "Having a settled friendship group at college"],
     "correctIndices": [0, 1, 2],
     "explanation": "Isolation, searching for identity, and unaddressed grievances are three of the vulnerability factors listed."},
    {"id": "l3y1-f-B03", "type": "scored",
     "prompt": "What's the deck's reframe of sharing personal information online?",
     "options": ["It's harmless if you're careful",
                 "Each piece - name, address, college, relationship status - is a lever; add location tags and shoot times and they tell a stranger where you will be",
                 "Only post on weekdays",
                 "Only share with classmates"],
     "answerIndex": 1,
     "explanation": "Each piece is a lever; location tags and shoot times tell a stranger where you will be."},
    {"id": "l3y1-f-B04", "type": "scored",
     "prompt": "What does the deck say about financial scams targeting students?",
     "options": ["They're rare",
                 "Students are a primary target - watch for paid edit or thumbnail gigs that ask for your bank details up front",
                 "They only target international students",
                 "Only via email"],
     "answerIndex": 1,
     "explanation": "Students are a primary target; watch for paid edit or thumbnail gigs that ask for your bank details up front."},
    {"id": "l3y1-f-B05", "type": "scored",
     "prompt": "What does the deck say about AI-generated images in consent?",
     "options": ["They're exempt from the law",
     "They're covered - non-consensual intimate images includes AI-generated images, and consent covers everyone you film or photograph, including classmates in your own footage",
     "They don't count as images",
     "They're only an issue if shared publicly"],
     "answerIndex": 1,
     "explanation": "Sharing intimate images without consent includes AI-generated images."},
    {"id": "l3y1-f-B06", "type": "insert",
     "prompt": "Fill in the blank: JCQ malpractice sanctions include disqualification and ____ from qualifications.",
     "template": "JCQ malpractice sanctions include disqualification and ____ from qualifications.",
     "options": ["debarment", "dismissal", "expulsion", "suspension"],
     "answerIndex": 0,
     "explanation": "Disqualification and debarment from qualifications."},
    {"id": "l3y1-f-B07", "type": "scored",
     "prompt": "What does the deck say about how concerns are logged?",
     "options": ["On paper only",
                 "All concerns are logged on ProMonitor",
                 "Only if escalated externally",
                 "Only by the Safeguarding Manager"],
     "answerIndex": 1,
     "explanation": "All concerns are logged on ProMonitor."},
    {"id": "l3y1-f-B08", "type": "insert",
     "prompt": "Fill in the blank: the Safeguarding Manager for Hastings is Lydia Leonard, 07848 ____.",
     "template": "The Safeguarding Manager for Hastings is Lydia Leonard, 07848 ____.",
     "options": ["123456", "442081", "668772", "049312"],
     "answerIndex": 1,
     "explanation": "Lydia Leonard, 07848 442081."},
    {"id": "l3y1-f-B09", "type": "scored",
     "prompt": "What's the deck's headline about how every concern is handled?",
     "options": ["Only logged if escalated",
                 "You will always be taken seriously. Every concern is logged, assessed, and followed up. There is no wrong way to raise it.",
                 "Only serious concerns are logged",
                 "Anonymous reports are ignored"],
     "answerIndex": 1,
     "explanation": "You will always be taken seriously. Every concern is logged, assessed, and followed up."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-f-C01", "type": "scored",
     "prompt": "How long is the Module F session?",
     "options": ["About 30 minutes", "About 60 minutes", "1.5 hours", "About 2.5 hours"],
     "answerIndex": 2,
     "explanation": "Module F runs 1.5 hours."},
    {"id": "l3y1-f-C02", "type": "scored",
     "prompt": "How does the deck define radicalisation?",
     "options": ["Holding extreme political views",
                 "The process by which someone comes to support terrorism or forms of extremism that lead to terrorism",
                 "Joining a protest",
                 "Reading online news"],
     "answerIndex": 1,
     "explanation": "Radicalisation is the process by which someone comes to support terrorism or forms of extremism that lead to terrorism."},
    {"id": "l3y1-f-C03", "type": "scored",
     "prompt": "Which phrase from the deck captures the Prevent message about debating politics?",
     "options": ["Avoid politics at all costs",
                 "Exploring ideas and debating politics is fine - and encouraged. Being pushed toward hatred of a group of people is not the same thing.",
                 "Only discuss politics with staff",
                 "Politics is banned at college"],
     "answerIndex": 1,
     "explanation": "Exploring ideas and debating politics is fine - and encouraged. Being pushed toward hatred of a group of people is not the same thing."},
    {"id": "l3y1-f-C04", "type": "scored",
     "prompt": "What does the deck say about personal data and public AI tools?",
     "options": ["Anything goes",
                 "Do not enter personal data into public AI tools - your name, address, college login, or details about other students or staff",
                 "Only enter your first name",
                 "Only enter it if logged in"],
     "answerIndex": 1,
     "explanation": "Do not enter personal data into public AI tools."},
    {"id": "l3y1-f-C05", "type": "multi",
     "prompt": "Which of these are part of the four-step safeguarding process? Select all that apply.",
     "options": ["Something is raised",
                 "The right person is told same-day",
                 "The concern is assessed",
                 "Confidentiality - honest about limits"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are the steps: Something is raised -> right person told same-day -> concern assessed -> confidentiality honest about its limits."},
    {"id": "l3y1-f-C06", "type": "insert",
     "prompt": "Fill in the blank: ESCG uses ____ for filtering and monitoring.",
     "template": "ESCG uses ____ for filtering and monitoring.",
     "options": ["Smoothwall", "Norton", "McAfee", "Sophos"],
     "answerIndex": 0,
     "explanation": "ESCG uses Smoothwall for filtering and monitoring."},
    {"id": "l3y1-f-C07", "type": "scored",
     "prompt": "Which is the deck's reframe of telling someone you're worried about a friend?",
     "options": ["It's a betrayal",
                 "It's the right thing to do - it's not a betrayal",
                 "It must wait until you're sure",
                 "Only your tutor can do it"],
     "answerIndex": 1,
     "explanation": "Acting on concern for a friend is the right thing. It is not a betrayal."},
    {"id": "l3y1-f-C08", "type": "scored",
     "prompt": "Which of these are options on the 'one thing' card? Select all that apply.",
     "options": ["Save the Safeguarding Team contact to my phone",
                 "Change one thing about how I share information online",
                 "Check the ESCG AI Policy and note one thing I didn't know",
                 "Tell someone about something that has been worrying me"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are the options on the 'one thing' card."},
    {"id": "l3y1-f-C09", "type": "multi",
     "prompt": "Which routes can you use to report a concern about yourself? Select all that apply.",
     "options": ["Talk to any member of staff you trust",
                 "Go directly to the Safeguarding Manager",
                 "Contact the Wellbeing Team - no referral needed",
                 "Email safeguarding@escg.ac.uk or report anonymously"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are routes you can use if you are worried about yourself."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-f-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")