#!/usr/bin/env python3
"""Quizzes A/B/C for Module H L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-h",
    "level": "l3",
    "year": "y1",
    "module": "H",
    "title": "How to Use Navigate",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-h-A01", "type": "scored",
     "prompt": "What's the deck's headline question that Navigate's Digital CV answers?",
     "options": ["Who are your friends?",
                 "What can you actually do, and how do you know?",
                 "How much homework do you have?",
                 "When do exams start?"],
     "answerIndex": 1,
     "explanation": "What can you actually do, and how do you know?"},
    {"id": "l3y1-h-A02", "type": "insert",
     "prompt": "Fill in the blank: ____ is where the real gains are - Red is usually already obvious to you.",
     "template": "____ is where the real gains are - Red is usually already obvious to you.",
     "options": ["Green", "Amber", "All three", "None of them"],
     "answerIndex": 1,
     "explanation": "Amber is where the real gains are."},
    {"id": "l3y1-h-A03", "type": "scored",
     "prompt": "What does the deck say about BA (Hons) at University Centre Hastings?",
     "options": ["You have to leave East Sussex",
                 "It's a degree without moving",
                 "It's only for Level 2 students",
                 "It's not part of Level 3"],
     "answerIndex": 1,
     "explanation": "BA (Hons) at University Centre Hastings - a degree without moving."},
    {"id": "l3y1-h-A04", "type": "scored",
     "prompt": "What does the deck say is the most useful outcome of the careers quiz?",
     "options": ["Picking the highest-paid job",
                 "A clear NO - ruling something out is progress, and it is faster than drifting into it",
                 "Matching your parents' expectations",
                 "Choosing the first option"],
     "answerIndex": 1,
     "explanation": "Ruling something out is progress, and it is faster than drifting into it."},
    {"id": "l3y1-h-A05", "type": "multi",
     "prompt": "Which of these should you log into Navigate? Select all that apply.",
     "options": ["Edits, builds and tests (Premiere Pro, DaVinci, Blender)",
                 "Live media - Youth Radio, Tag magazine, The Depot",
                 "Industry placement - 315 hours on the T Levels",
                 "Only Final Major Projects"],
     "correctIndices": [0, 1, 2],
     "explanation": "Edits/builds/tests, live media, and the 315-hour placement are all on the logging list."},
    {"id": "l3y1-h-A06", "type": "scored",
     "prompt": "What does the deck say makes the analytical reflection better?",
     "options": ["It's longer",
                 "It names the decision, the reasoning, the evidence and the change in practice",
                 "It uses technical vocabulary",
                 "It avoids emotion"],
     "answerIndex": 1,
     "explanation": "The analytical version names the decision, the reasoning, the evidence and the change in practice."},
    {"id": "l3y1-h-A07", "type": "scored",
     "prompt": "How does the deck frame asking for help on the Navigate tasks?",
     "options": ["As weakness",
                 "As a professional skill, not a weakness",
                 "As a last resort",
                 "As something to avoid"],
     "answerIndex": 1,
     "explanation": "Asking early is a professional skill, not a weakness."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-h-B01", "type": "scored",
     "prompt": "What's the deck's view of the Skills Assessment?",
     "options": ["It's an objective test",
                 "It's a self-report - its value depends entirely on your honesty",
                 "It's marked by your tutor",
                 "It doesn't matter"],
     "answerIndex": 1,
     "explanation": "Its value depends entirely on your honesty - inflate it and you get a useless picture of yourself."},
    {"id": "l3y1-h-B02", "type": "scored",
     "prompt": "What does the deck say UCAS requires, and when?",
     "options": ["UCAS runs in Year 1; the material for a personal statement is built in Year 2",
                 "UCAS runs in Year 2; the material for a personal statement is built in Year 1",
                 "UCAS runs after you leave college",
                 "UCAS is optional"],
     "answerIndex": 1,
     "explanation": "UCAS runs in Year 2; the material for a personal statement is built in Year 1."},
    {"id": "l3y1-h-B03", "type": "insert",
     "prompt": "Fill in the blank: the T Levels require ____ hours of industry placement.",
     "template": "The T Levels require ____ hours of industry placement.",
     "options": ["50", "100", "200", "315"],
     "answerIndex": 3,
     "explanation": "Industry placement - 315 hours on the T Levels."},
    {"id": "l3y1-h-B04", "type": "scored",
     "prompt": "What's the deck's logging rule?",
     "options": ["Log at the end of year 2",
                 "One entry per activity, logged the same week, tagged to the skills it evidences - ten minutes now saves an afternoon in Year 2",
                 "Only log assessed units",
                 "Only log live media"],
     "answerIndex": 1,
     "explanation": "One entry per activity, logged the same week, tagged to the skills it evidences."},
    {"id": "l3y1-h-B05", "type": "scored",
     "prompt": "What does the deck say about Year 1 in relation to Year 2?",
     "options": ["Year 1 is a warm-up",
                 "Year 1 sets the trajectory of Year 2 - it is not a warm-up",
                 "Year 1 doesn't count",
                 "Year 1 is just induction"],
     "answerIndex": 1,
     "explanation": "Year 1 sets the trajectory of Year 2 - it is not a warm-up."},
    {"id": "l3y1-h-B06", "type": "multi",
     "prompt": "Which of these are in the first-two-weeks checklist? Select all that apply.",
     "options": ["Skills Assessment completed honestly",
                 "Next Destination set, entry requirements checked",
                 "Career Quiz completed, every profile reviewed",
                 "Digital CV Introduction written"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are in the eight-item checklist."},
    {"id": "l3y1-h-B07", "type": "scored",
     "prompt": "What does the deck say about part-time work?",
     "options": ["Don't bother logging it",
                 "Professionalism and communication are the same skills - log it",
                 "It doesn't help your Digital CV",
                 "Only paid work in the industry counts"],
     "answerIndex": 1,
     "explanation": "Part-time work - professionalism and communication are the same skills."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-h-C01", "type": "scored",
     "prompt": "What's the headline framing of Navigate in the deck?",
     "options": ["A timetabling tool",
     "Where you build the evidence that you did",
     "A library catalogue",
     "A reporting system"],
     "answerIndex": 1,
     "explanation": "Navigate is where you build the evidence that you did."},
    {"id": "l3y1-h-C02", "type": "scored",
     "prompt": "Which band says 'inconsistent under pressure - most people sit here'?",
     "options": ["Green", "Amber", "Red", "None of them"],
     "answerIndex": 1,
     "explanation": "Amber - inconsistent under pressure; most people sit here."},
    {"id": "l3y1-h-C03", "type": "scored",
     "prompt": "What does the deck say you should do with each careers quiz profile?",
     "options": ["Click through quickly",
                 "Interrogate each profile: entry route, qualification level, earnings, and what the job is like day to day",
                 "Pick the highest-paid one",
                 "Pick the first one"],
     "answerIndex": 1,
     "explanation": "Interrogate each profile: entry route, qualification level, earnings, and what the job is like day to day."},
    {"id": "l3y1-h-C04", "type": "insert",
     "prompt": "Fill in the blank: two years of consistent logging becomes a portfolio; two years of good intentions becomes a ____ in February.",
     "template": "Two years of consistent logging becomes a portfolio; two years of good intentions becomes a ____ in February.",
     "options": ["holiday", "panic", "win", "vacancy"],
     "answerIndex": 1,
     "explanation": "Two years of good intentions becomes a panic in February."},
    {"id": "l3y1-h-C05", "type": "multi",
     "prompt": "Which of these are on the deck's logging list? Select all that apply.",
     "options": ["Film, audio, graphics and code you plan, make and evaluate",
                 "Externally moderated projects and Final Major Projects",
                 "Visiting media professionals and industry visits",
                 "Cross-department work (e.g. photographing for Hair and Beauty)"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are on the logging list."},
    {"id": "l3y1-h-C06", "type": "scored",
     "prompt": "What does the deck say about Reflection Coach?",
     "options": ["It does the reflection for you",
                 "It prompts you towards the standard - it does not do it for you, and an assessor can tell the difference",
                 "It's optional",
                 "It's not used in this department"],
     "answerIndex": 1,
     "explanation": "Reflection Coach prompts you towards this - it does not do it for you, and an assessor can tell the difference."},
    {"id": "l3y1-h-C07", "type": "scored",
     "prompt": "By when must the eight first-two-weeks tasks be completed?",
     "options": ["End of week 1", "End of week 2", "End of week 4", "End of term"],
     "answerIndex": 1,
     "explanation": "Complete these independently by the end of week two."},
    {"id": "l3y1-h-C08", "type": "scored",
     "prompt": "What's the deck's framing of asking for help on these tasks?",
     "options": ["It's weakness",
                 "Asking early is a professional skill, not a weakness",
                 "It's only acceptable once",
                 "Only at the end"],
     "answerIndex": 1,
     "explanation": "Asking early is a professional skill, not a weakness."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-h-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")