#!/usr/bin/env python3
"""Quizzes A/B/C for Module K L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-k",
    "level": "l3",
    "year": "y1",
    "module": "K",
    "title": "Progression Opportunities & Setting Goals",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-k-A01", "type": "scored",
     "prompt": "Which PROUD value is this module grounded in?",
     "options": ["Show Respect", "Encourage Unity", "Seek Opportunity", "Be Proud"],
     "answerIndex": 2,
     "explanation": "Seek Opportunity - the same value that opened the programme."},
    {"id": "l3y1-k-A02", "type": "scored",
     "prompt": "How many progression routes does the deck map?",
     "options": ["Three", "Four", "Five", "Seven"],
     "answerIndex": 2,
     "explanation": "Five routes."},
    {"id": "l3y1-k-A03", "type": "multi",
     "prompt": "Which are the five routes in the deck? Select all that apply.",
     "options": ["University & higher education", "Degree apprenticeships",
                 "Apprenticeships", "Skilled employment", "Further study"],
     "correctIndices": [0, 1, 2, 3, 4],
     "explanation": "All five are the routes."},
    {"id": "l3y1-k-A04", "type": "scored",
     "prompt": "What's the deck's headline about opportunities evidence?",
     "options": ["Half-remembered anecdotes",
                 "Dated evidence - not half-remembered anecdotes; this is what references are written from",
                 "Only paid work counts",
                 "Only what your tutor remembers"],
     "answerIndex": 1,
     "explanation": "Dated evidence - not half-remembered anecdotes."},
    {"id": "l3y1-k-A05", "type": "scored",
     "prompt": "What's the deck's test for whether something is a goal rather than an aspiration?",
     "options": ["It must be SMART",
                 "Does it tell you what to do next week? If not, it is still an aspiration",
                 "It must mention university",
                 "It must be approved by a tutor"],
     "answerIndex": 1,
     "explanation": "Does it tell you what to do next week?"},
    {"id": "l3y1-k-A06", "type": "dragorder",
     "prompt": "Put the three horizons in the order the deck presents them.",
     "items": ["This term", "This year", "On completion"],
     "solution": [0, 1, 2],
     "explanation": "Short-term, medium-term, long-term."},
    {"id": "l3y1-k-A07", "type": "scored",
     "prompt": "What does the deck say to do if you are unsure the course is right?",
     "options": ["Wait until next term",
                 "Say so now. Waiting does not keep your options open - it closes them",
                 "Switch without telling anyone",
                 "Drop out"],
     "answerIndex": 1,
     "explanation": "If you are unsure, say so now. Waiting does not keep your options open - it closes them."},
    {"id": "l3y1-k-A08", "type": "scored",
     "prompt": "What's the deck's closing line?",
     "options": ["'Good luck'",
                 "'Three weeks ago you were given a timetable. Today you gave yourself a goal. Things stop being given and start being taken. Go take them.'",
                 "'See you next term'",
                 "'Practice makes perfect'"],
     "answerIndex": 1,
     "explanation": "Things stop being given and start being taken. Go take them."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-k-B01", "type": "scored",
     "prompt": "What does the deck say about the most common route?",
     "options": ["It is the only route",
                 "The most common route is not automatically your route",
                 "It's a backup",
                 "It's compulsory"],
     "answerIndex": 1,
     "explanation": "The most common route is not automatically your route."},
    {"id": "l3y1-k-B02", "type": "scored",
     "prompt": "Which degree-apprenticeship level is named in the deck?",
     "options": ["Level 2", "Level 3", "Level 5 and Level 6", "Level 7 only"],
     "answerIndex": 2,
     "explanation": "Level 5 and Level 6 Higher Apprenticeships."},
    {"id": "l3y1-k-B03", "type": "multi",
     "prompt": "Which of these are the three Navigate pillars the deck mentions? Select all that apply.",
     "options": ["My Digital CV", "Skills Assessment", "Opportunities record", "A printed portfolio"],
     "correctIndices": [0, 1, 2],
     "explanation": "My Digital CV, Skills Assessment, and Opportunities record are the three pillars."},
    {"id": "l3y1-k-B04", "type": "scored",
     "prompt": "What's the deck's framing of the Navigate record?",
     "options": ["A college admin task",
                 "A live professional portfolio that develops over two years, not a college admin task",
                 "Something you fill in at the end of Year 2",
                 "Something only placement providers see"],
     "answerIndex": 1,
     "explanation": "A live professional portfolio that develops over two years."},
    {"id": "l3y1-k-B05", "type": "scored",
     "prompt": "According to the deck, what's the difference between 'the course is hard' and 'the course is wrong'?",
     "options": ["No difference",
                 "Hard is normal Level 3 feeling, answered with support; wrong is a different subject/level/route and needs a conversation this week",
                 "Hard means you should drop out",
                 "Wrong means your tutor will move you"],
     "answerIndex": 1,
     "explanation": "Hard is answered with support; wrong needs a conversation this week."},
    {"id": "l3y1-k-B06", "type": "scored",
     "prompt": "What happens to fees already paid under the Right Choice window?",
     "options": ["They're lost",
                 "They transfer automatically to a new course under Right Choice",
                 "You have to apply again",
                 "Only if you have an extenuating circumstance"],
     "answerIndex": 1,
     "explanation": "Course fees already paid transfer automatically under Right Choice."},
    {"id": "l3y1-k-B07", "type": "multi",
     "prompt": "Which of these are the three contacts that outlive induction? Select all that apply.",
     "options": ["Careers Team", "Personal tutor", "Head of Curriculum", "Only your tutor"],
     "correctIndices": [0, 1, 2],
     "explanation": "Careers Team, Personal tutor, and Head of Curriculum."},
    {"id": "l3y1-k-B08", "type": "multi",
     "prompt": "Which of these are options on the 'one goal' card? Select all that apply.",
     "options": ["My goal for this term is ... and my first step this week is ...",
                 "I will bring Navigate up to date this week",
                 "I will book a Careers conversation about what my next step actually requires",
                 "I am not sure this is the right course - I will talk to my tutor this week"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are options on the 'one goal' card."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-k-C01", "type": "scored",
     "prompt": "How long is the Module K session?",
     "options": ["About 30 minutes", "About 60 minutes", "90 minutes", "About 2 hours"],
     "answerIndex": 2,
     "explanation": "Module K is 90 minutes."},
    {"id": "l3y1-k-C02", "type": "scored",
     "prompt": "What does the deck say about university as a route?",
     "options": ["It's the default",
     "It's one of five real doors - not the default",
     "It's compulsory",
     "It's not on the map"],
     "answerIndex": 1,
     "explanation": "It's one of five real doors."},
    {"id": "l3y1-k-C03", "type": "scored",
     "prompt": "What does the deck say about Digital Content Creator?",
     "options": ["It's a degree",
     "It's an apprenticeship route",
     "It's a university degree",
     "It's only for Year 2"],
     "answerIndex": 1,
     "explanation": "Digital Content Creator is one of the apprenticeship routes."},
    {"id": "l3y1-k-C04", "type": "scored",
     "prompt": "What's the deck's view on Navigate evidence?",
     "options": ["'We'll do my CV when I need it'",
     "'Nobody remembers in March what they did in October. Navigate remembers. That is the whole trick.'",
     "'CVs are optional'",
     "'Only tutors see the record'"],
     "answerIndex": 1,
     "explanation": "Nobody remembers in March what they did in October. Navigate remembers."},
    {"id": "l3y1-k-C05", "type": "scored",
     "prompt": "What's the deck's example of a goal (T Level / Cybersecurity)?",
     "options": ["'I want to be a film director'",
     "'By October half-term I have researched three potential placement employers and drafted my first contact. First step: check placement requirements with my teacher today.'",
     "'I want to work in games'",
     "'I want to design content for a living'"],
     "answerIndex": 1,
     "explanation": "Specific date, first step, evidence of action."},
    {"id": "l3y1-k-C06", "type": "scored",
     "prompt": "According to the deck, what's the right time to act on course-fit doubt?",
     "options": ["At the end of Year 2",
     "Three weeks in is exactly when doubt surfaces. Say so now - waiting closes your options",
     "After graduation",
     "Only at open evening"],
     "answerIndex": 1,
     "explanation": "Three weeks in is exactly when doubt surfaces. Say so now."},
    {"id": "l3y1-k-C07", "type": "scored",
     "prompt": "What's the closing line of Module K?",
     "options": ["'Good luck'",
     "'Three weeks ago you were given a timetable. Today you gave yourself a goal. Things stop being given and start being taken. Go take them.'",
     "'See you next term'",
     "'Practice makes perfect'"],
     "answerIndex": 1,
     "explanation": "Things stop being given and start being taken. Go take them."},
    {"id": "l3y1-k-C08", "type": "scored",
     "prompt": "What's the deck's framing of three-horizon planning?",
     "options": ["Pick any one",
     "Draft one goal for each horizon; start with the long one, then work backwards - does your term goal actually lead there?",
     "Only plan the short term",
     "Skip the medium horizon"],
     "answerIndex": 1,
     "explanation": "Start with the long one, then work backwards."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-k-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")