#!/usr/bin/env python3
"""Quizzes A/B/C for Module G L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-g",
    "level": "l3",
    "year": "y1",
    "module": "G",
    "title": "Looking After Myself",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-g-A01", "type": "scored",
     "prompt": "Which PROUD value is this module grounded in?",
     "options": ["Seek Opportunity", "Show Respect", "Encourage Unity", "Be Proud"],
     "answerIndex": 2,
     "explanation": "Encourage Unity - looking out for each other."},
    {"id": "l3y1-g-A02", "type": "insert",
     "prompt": "Fill in the blank: the mental-health spectrum runs Thriving -> Coping -> Struggling -> ____.",
     "template": "The mental-health spectrum runs Thriving -> Coping -> Struggling -> ____.",
     "options": ["Happy", "In Crisis", "Asleep", "Studying"],
     "answerIndex": 1,
     "explanation": "Thriving -> Coping -> Struggling -> In Crisis."},
    {"id": "l3y1-g-A03", "type": "scored",
     "prompt": "What does the deck say about the six things that move the mental-health line?",
     "options": ["They're character flaws",
                 "Not one is a character flaw - they're conditions, and most can be worked on",
                 "Only sleep matters",
                 "They can't be changed"],
     "answerIndex": 1,
     "explanation": "Not one of those six things is a character flaw - they're conditions."},
    {"id": "l3y1-g-A04", "type": "multi",
     "prompt": "Which are the four evidence-based moves the deck lists for stress? Select all that apply.",
     "options": ["Move", "Connect", "Sleep", "Talk"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "Move, Connect, Sleep, Talk."},
    {"id": "l3y1-g-A05", "type": "scored",
     "prompt": "Why does the deck say sleep matters for your grades?",
     "options": ["It doesn't matter",
                 "Memory is built while you sleep - revision without sleep is pouring water into a cracked jug",
                 "It only matters at weekends",
                 "Coffee works just as well"],
     "answerIndex": 1,
     "explanation": "Memory is built while you sleep - revision without sleep is pouring water into a cracked jug."},
    {"id": "l3y1-g-A06", "type": "scored",
     "prompt": "What's the deck's headline about using support at ESCG?",
     "options": ["A last resort",
                 "Normal and expected - and it goes on no record that follows you",
                 "Only for diagnosed students",
                 "Something to keep quiet"],
     "answerIndex": 1,
     "explanation": "Normal and expected - and it goes on no record that follows you."},
    {"id": "l3y1-g-A07", "type": "scored",
     "prompt": "How does the deck reframe telling someone about a friend's serious disclosure?",
     "options": ["It's a betrayal",
                 "You can be loyal and still tell someone - those aren't opposites",
                 "Only if the friend agrees first",
                 "Never tell anyone"],
     "answerIndex": 1,
     "explanation": "You can be loyal and still tell someone. Those aren't opposites."},
    {"id": "l3y1-g-A08", "type": "insert",
     "prompt": "Fill in the blank: Samaritans is ____.",
     "template": "Samaritans is ____.",
     "options": ["116 123 - free, 24/7", "0300 999 9999", "0800 111 1111", "999"],
     "answerIndex": 0,
     "explanation": "Samaritans: 116 123 - free, 24/7."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-g-B01", "type": "scored",
     "prompt": "What's the highest-leverage sleep change the deck recommends?",
     "options": ["Buy a new mattress",
                 "Anchor your wake time - same time every day, including one weekend day",
                 "Avoid all screens",
                 "Take sleeping pills"],
     "answerIndex": 1,
     "explanation": "Anchor your wake time - same time every day, including one weekend day."},
    {"id": "l3y1-g-B02", "type": "scored",
     "prompt": "How does the deck reframe money worries?",
     "options": ["Something to keep quiet",
                 "Money worries are a reason to talk to us - not a reason to disappear",
                 "Only students with debt qualify",
                 "They're rare"],
     "answerIndex": 1,
     "explanation": "Money worries are a reason to talk to us - not a reason to disappear."},
    {"id": "l3y1-g-B03", "type": "scored",
     "prompt": "How does the deck describe the Hardship Fund?",
     "options": ["A loan",
                 "Emergency financial support for travel, food, equipment, sudden changes at home - asking is confidential, and far more common than you'd think",
                 "Only for travel",
                 "Restricted to international students"],
     "answerIndex": 1,
     "explanation": "Emergency financial support - asking is confidential, and far more common than you'd think."},
    {"id": "l3y1-g-B04", "type": "insert",
     "prompt": "Fill in the blank: MIND is ____.",
     "template": "MIND is ____.",
     "options": ["116 123", "0300 123 3393 / mind.org.uk", "07848 442081", "999"],
     "answerIndex": 1,
     "explanation": "MIND: 0300 123 3393 / mind.org.uk."},
    {"id": "l3y1-g-B05", "type": "scored",
     "prompt": "What's the deck's three-step pathway for support?",
     "options": ["Fill in form, wait, get a letter",
                 "Say something -> Referral -> Support arranged",
                 "Tell your parents -> wait -> email your tutor",
                 "Apply online -> take a test -> get a result"],
     "answerIndex": 1,
     "explanation": "Say something -> Referral -> Support arranged."},
    {"id": "l3y1-g-B06", "type": "scored",
     "prompt": "What's the deck's view on self-disclosing a disability or learning need?",
     "options": ["Don't bother",
                 "Sharing it means support can actually be arranged - exam access, adjustments, the right help at the right time",
                 "Only if it affects attendance",
                 "Only at enrolment"],
     "answerIndex": 1,
     "explanation": "Sharing it means support can actually be arranged."},
    {"id": "l3y1-g-B07", "type": "multi",
     "prompt": "Which of these are options on the 'one thing' card? Select all that apply.",
     "options": ["Sleep - I'll anchor my wake time",
                 "Pressure valve - I'll put one deliberate non-work thing in my week",
                 "Contacts - I'll save the support numbers and find the Wellbeing Team's door",
                 "Talk - I'll tell my tutor or the Wellbeing Team about something getting in the way"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are options on the 'one thing' card."},
    {"id": "l3y1-g-B08", "type": "scored",
     "prompt": "What's the deck's closing line about telling someone?",
     "options": ["Telling someone is never the wrong call",
                 "Telling someone is rarely helpful",
                 "Always ask the friend first",
                 "Only tell someone if it's urgent"],
     "answerIndex": 0,
     "explanation": "Look out for each other. Telling someone is never the wrong call."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-g-C01", "type": "scored",
     "prompt": "How long is the Module G session?",
     "options": ["About 30 minutes", "About 60 minutes", "90 minutes", "About 2.5 hours"],
     "answerIndex": 2,
     "explanation": "Module G is 90 minutes."},
    {"id": "l3y1-g-C02", "type": "scored",
     "prompt": "What's the deck's headline framing of mental health?",
     "options": ["Mental health is private",
                 "Mental health is health - and the line can be moved",
                 "Mental health is overdiagnosed",
                 "Mental health is for tutors to worry about"],
     "answerIndex": 1,
     "explanation": "Mental health is health - and the line can be moved."},
    {"id": "l3y1-g-C03", "type": "scored",
     "prompt": "How does the deck describe naming your stress to a friend?",
     "options": ["It makes it worse",
                 "Naming it to someone halves its size, every time",
                 "Only useful with a counsellor",
                 "Only in writing"],
     "answerIndex": 1,
     "explanation": "Naming it to someone halves its size, every time."},
    {"id": "l3y1-g-C04", "type": "multi",
     "prompt": "Which contacts does the deck say students MUST leave with? Select all that apply.",
     "options": ["Samaritans 116 123", "MIND 0300 123 3393 / mind.org.uk",
                 "iRock - drop-in support for young people in East Sussex",
                 "TogetherAll - free, anonymous online support community"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are on the contacts card students must leave with."},
    {"id": "l3y1-g-C05", "type": "scored",
     "prompt": "What's the deck's view on asking the Wellbeing Team for help?",
     "options": ["It's a last resort",
                 "Any door works - you can go straight to the Wellbeing Team; no referral needed",
                 "Only with a doctor's note",
                 "Only in writing"],
     "answerIndex": 1,
     "explanation": "Any door works - you can go straight to the Wellbeing Team."},
    {"id": "l3y1-g-C06", "type": "insert",
     "prompt": "Fill in the blank: the deck's sleep line is 'memory is built while you ____'.",
     "template": "The deck's sleep line is 'memory is built while you ____'.",
     "options": ["study", "sleep", "scroll", "snack"],
     "answerIndex": 1,
     "explanation": "Memory is built while you sleep."},
    {"id": "l3y1-g-C07", "type": "scored",
     "prompt": "What's the deck's 'ask' line for looking out for each other?",
     "options": ["\"Are you OK?\" (no follow-up)",
                 "\"You alright? Actually alright?\" - then listen to the answer",
                 "\"Why aren't you in lessons?\"",
                 "\"Snap out of it.\""],
     "answerIndex": 1,
     "explanation": "'You alright? Actually alright?' Then listen to the answer."},
    {"id": "l3y1-g-C08", "type": "scored",
     "prompt": "How does the deck describe asking for help at ESCG?",
     "options": ["Something embarrassing",
                 "Normal and expected - and it goes on no record that follows you",
                 "Only for diagnosed students",
                 "A sign of weakness"],
     "answerIndex": 1,
     "explanation": "Normal and expected - and it goes on no record that follows you."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-g-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")