#!/usr/bin/env python3
"""Generate quiz A/B/C for Module D L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-d",
    "level": "l3",
    "year": "y1",
    "module": "D",
    "title": "Students' Voice & Student Rep Elections",
    "note": "Content sourced from the Year 2 / L3 variant of this deck (see SOURCE_OF_TRUTH note in the PowerPoint's teacher appendix). Swap when a true Year 1 deck is provided."
}

quiz_a = {
    "meta": {**META, "variant": "A"},
    "questions": [
        {"id": "l3y1-d-A01", "type": "scored",
         "prompt": "Which PROUD value is Module D grounded in?",
         "options": ["Seek Opportunity", "Show Respect", "Encourage Unity", "Be Proud"],
         "answerIndex": 2,
         "explanation": "Module D is grounded in Encourage Unity."},
        {"id": "l3y1-d-A02", "type": "scored",
         "prompt": "Which of these is an example of feedback that 'names the thing'?",
         "options": ["'The software is rubbish'", "'Four edit stations can't run Premiere'",
                     "'The course could be better'", "'Things would be good if they were better'"],
         "answerIndex": 1,
         "explanation": "'Four edit stations can't run Premiere' beats 'the software is rubbish'."},
        {"id": "l3y1-d-A03", "type": "multi",
         "prompt": "Which are the four 'ways to get involved' in the deck? Select all that apply.",
         "options": ["Student Rep", "Student Governor", "NUS Membership (TOTUM card)", "Surveys & Forums"],
         "correctIndices": [0, 1, 2, 3],
         "explanation": "All four are the ways to get involved."},
        {"id": "l3y1-d-A04", "type": "scored",
         "prompt": "How many Student Council meetings per year does a rep attend?",
         "options": ["1", "3", "6", "12"],
         "answerIndex": 1,
         "explanation": "Reps attend 3 Student Council meetings per year."},
        {"id": "l3y1-d-A05", "type": "scored",
         "prompt": "How many Student Governor places are on the Main Governing Board?",
         "options": ["1", "3", "5", "7"],
         "answerIndex": 1,
         "explanation": "There are 3 Student Governor places on the Main Governing Board."},
        {"id": "l3y1-d-A06", "type": "insert",
         "prompt": "Fill in the blank: Student Governor applications close at midday on Friday ____ October.",
         "template": "Student Governor applications close at midday on Friday ____ October.",
         "options": ["9th", "16th", "23rd", "30th"],
         "answerIndex": 1,
         "explanation": "Applications close at midday, Friday 16 October."},
        {"id": "l3y1-d-A07", "type": "scored",
         "prompt": "How does the deck describe the difference between one person's complaint and a group's view?",
         "options": ["Both are opinions",
                     "One is an opinion; a group saying the same thing is evidence - and evidence is what changes decisions",
                     "A single complaint carries more weight than a group",
                     "Only written complaints count"],
         "answerIndex": 1,
         "explanation": "One person's complaint is an opinion. A group saying the same thing is evidence - and evidence is what changes decisions."},
        {"id": "l3y1-d-A08", "type": "multi",
         "prompt": "Which are stages of the election in the deck? Select all that apply.",
         "options": ["Nominations", "Candidate pitches", "The vote", "Confirm & register"],
         "correctIndices": [0, 1, 2, 3],
         "explanation": "All four are the stages: Nominations -> Pitches -> Vote -> Confirm & register."}
    ]
}

quiz_b = {
    "meta": {**META, "variant": "B"},
    "questions": [
        {"id": "l3y1-d-B01", "type": "dragorder",
         "prompt": "Put the eight beats of this session in the order the deck presents them.",
         "items": ["Check-in", "Students' Voice", "Ways to get involved", "The Rep role",
                   "The Governor role", "Encourage Unity (PROUD)", "Election", "Close"],
         "solution": [0, 1, 2, 3, 4, 5, 6, 7],
         "explanation": "These are the eight beats in the order the deck presents them."},
        {"id": "l3y1-d-B02", "type": "multi",
         "prompt": "Which are conditions for student voice actually working, according to the deck? Select all that apply.",
         "options": [
             "Reps who actually consult their group - not just improvise at meetings",
             "Feedback that names the thing",
             "Groups who tell their rep what matters before the meeting, not after",
             "Students who follow up after the meeting"
         ],
         "correctIndices": [0, 1, 2, 3],
         "explanation": "All four are the conditions for student voice to actually work."},
        {"id": "l3y1-d-B03", "type": "scored",
         "prompt": "How much does the TOTUM card cost per year, according to the deck?",
         "options": ["Free", "£4.99", "£14.99", "£24.99"],
         "answerIndex": 2,
         "explanation": "TOTUM card costs £14.99/year."},
        {"id": "l3y1-d-B04", "type": "scored",
         "prompt": "When is Student Rep training, according to the deck?",
         "options": ["Wednesday 7 October", "Wednesday 14 October", "Wednesday 21 October", "Wednesday 28 October"],
         "answerIndex": 1,
         "explanation": "Rep training: Wednesday 14 October (all campuses) - mandatory for newly elected reps."},
        {"id": "l3y1-d-B05", "type": "scored",
         "prompt": "Which best describes the Governor role, compared with the Rep role?",
         "options": ["Day-to-day management of the college",
                     "Strategic scope and institutional weight, not group representation",
                     "Same as the Rep role but with more meetings",
                     "A paid part-time job"],
         "answerIndex": 1,
         "explanation": "The Governor role is different from Student Rep: strategic scope and institutional weight."},
        {"id": "l3y1-d-B06", "type": "insert",
         "prompt": "Fill in the blank: the Governor commitment is roughly ____ hours a month.",
         "template": "The Governor commitment is roughly ____ hours a month.",
         "options": ["1-2", "3-5", "8-10", "12-15"],
         "answerIndex": 1,
         "explanation": "Roughly 3-5 hours a month, across the academic year."},
        {"id": "l3y1-d-B07", "type": "scored",
         "prompt": "Who is the Director of Governance you can contact about applying?",
         "options": ["Chelsey King", "Tessa Echalaz", "Paige Baker-Carroll", "Belle Howard"],
         "answerIndex": 3,
         "explanation": "Director of Governance: Belle Howard, Belle.Howard@escg.ac.uk."},
        {"id": "l3y1-d-B08", "type": "scored",
         "prompt": "By when must Student Rep elections be completed and the rep confirmed?",
         "options": ["End of Week 1", "End of Week 2", "End of Week 4", "End of term"],
         "answerIndex": 1,
         "explanation": "Student Rep elections must be completed and the rep confirmed no later than the end of Week 2."}
    ]
}

quiz_c = {
    "meta": {**META, "variant": "C"},
    "questions": [
        {"id": "l3y1-d-C01", "type": "scored",
         "prompt": "How long is the Module D session?",
         "options": ["About 30 minutes", "About 60 minutes", "About 100 minutes", "About 2 hours"],
         "answerIndex": 2,
         "explanation": "Module D is around 100 minutes long."},
        {"id": "l3y1-d-C02", "type": "scored",
         "prompt": "How many seats are elected today?",
         "options": ["One - the course rep", "Two - the course rep and the English/maths rep",
                     "Three - course rep, English/maths rep, and a Governor",
                     "None - they're appointed later"],
         "answerIndex": 1,
         "explanation": "Two seats are elected today: course rep and English/maths rep."},
        {"id": "l3y1-d-C03", "type": "scored",
         "prompt": "What is the eligibility requirement to apply for Student Governor?",
         "options": ["Any current student, in any year",
                     "Students planning to study at ESCG for at least one more year",
                     "Only Year 1 students",
                     "Only students with a UCAS offer"],
         "answerIndex": 1,
         "explanation": "You must be planning to study at ESCG for at least one more year."},
        {"id": "l3y1-d-C04", "type": "insert",
         "prompt": "Fill in the blank: the TOTUM card costs ____ per year.",
         "template": "The TOTUM card costs ____ per year.",
         "options": ["£4.99", "£9.99", "£14.99", "£24.99"],
         "answerIndex": 2,
         "explanation": "TOTUM card costs £14.99/year."},
        {"id": "l3y1-d-C05", "type": "scored",
         "prompt": "When does the Induction Survey open, according to the deck?",
         "options": ["3 October", "3 November", "3 December", "3 January"],
         "answerIndex": 1,
         "explanation": "The Induction Survey opens 3 November."},
        {"id": "l3y1-d-C06", "type": "multi",
         "prompt": "Which are stages of the Governor application process, in order? Select all that apply.",
         "options": ["Submit online nomination form by midday, Fri 16 October",
                     "Informal conversation about your interest (2-5 November)",
                     "Student ballot if more candidates than places (9-23 November)",
                     "Committee recommendation 24 November; Board appointment 14 December"],
         "correctIndices": [0, 1, 2, 3],
         "explanation": "All four are the stages of the Governor application process."},
        {"id": "l3y1-d-C07", "type": "scored",
         "prompt": "Which phrase from the deck captures the Encourage Unity message?",
         "options": ["'Only senior staff get to decide.'",
                     "'One person's complaint is an opinion. A group saying the same thing is evidence.'",
                     "'Always complain in writing.'",
                     "'Speak only through your tutor.'"],
         "answerIndex": 1,
         "explanation": "One person's complaint is an opinion. A group saying the same thing is evidence - and evidence is what changes decisions."},
        {"id": "l3y1-d-C08", "type": "scored",
         "prompt": "Which commitment is described as 'genuinely CV-worthy at this level'?",
         "options": ["Attending Student Council meetings",
                     "Standing as a Student Governor",
                     "Filling in the Induction Survey",
                     "Joining the TOTUM discount scheme"],
         "answerIndex": 1,
         "explanation": "The Student Governor role is described as 'exceptional leadership experience - genuinely CV-worthy at this level'."}
    ]
}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-d-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")