#!/usr/bin/env python3
"""Quizzes A/B/C for Module J L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-j",
    "level": "l3",
    "year": "y1",
    "module": "J",
    "title": "Work Experience",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-j-A01", "type": "scored",
     "prompt": "Which PROUD value is this module grounded in?",
     "options": ["Show Respect", "Encourage Unity", "Seek Opportunity", "Be Proud"],
     "answerIndex": 2,
     "explanation": "Seek Opportunity."},
    {"id": "l3y1-j-A02", "type": "scored",
     "prompt": "What does the deck say work experience is?",
     "options": ["An add-on to your course",
                 "The part of your training that happens outside college - not an add-on",
                 "Something optional",
                 "Only for T Level students"],
     "answerIndex": 1,
     "explanation": "It's not an add-on - it's the part of your training that happens outside college."},
    {"id": "l3y1-j-A03", "type": "multi",
     "prompt": "Which are types of work experience the deck lists? Select all that apply.",
     "options": ["Block placement", "Employer visits", "Volunteering",
                 "Live project briefs", "Industry partnerships"],
     "correctIndices": [0, 1, 2, 3, 4],
     "explanation": "All five are listed."},
    {"id": "l3y1-j-A04", "type": "scored",
     "prompt": "How long is a T Level industry placement, approximately?",
     "options": ["30 hours", "100 hours", "315 hours", "1000 hours"],
     "answerIndex": 2,
     "explanation": "Around 315 hours on the T Levels."},
    {"id": "l3y1-j-A05", "type": "insert",
     "prompt": "Fill in the blank: Skills Week is Monday ____ March 2027.",
     "template": "Skills Week is Monday ____ March 2027.",
     "options": ["1st", "8th", "15th", "22nd"],
     "answerIndex": 1,
     "explanation": "Monday 8 March 2027."},
    {"id": "l3y1-j-A06", "type": "scored",
     "prompt": "Within what hours must placements fit?",
     "options": ["7am-7pm", "8.30am-5.30pm", "9am-5pm", "24/7"],
     "answerIndex": 1,
     "explanation": "8.30am-5.30pm, max 8-hour day."},
    {"id": "l3y1-j-A07", "type": "scored",
     "prompt": "Where does Navigate live, according to the deck?",
     "options": ["On the college app",
                 "Inside My Student Life - or go straight to login.navigate.uk.com",
                 "On your tutor's laptop",
                 "On a USB stick"],
     "answerIndex": 1,
     "explanation": "Navigate lives inside My Student Life."},
    {"id": "l3y1-j-A08", "type": "scored",
     "prompt": "What's the deck's headline about logging hours?",
     "options": ["Log at the end of the week",
                 "Complete your Navigate journal and timesheet every day you attend; record what you actually did",
                 "Only log assessed tasks",
                 "Logging is optional"],
     "answerIndex": 1,
     "explanation": "Complete your Navigate journal and timesheet every day you attend."},
    {"id": "l3y1-j-A09", "type": "scored",
     "prompt": "What's the deck's closing line?",
     "options": ["'Good luck'",
                 "'In this industry you are hired on what you can show and who will vouch for you - a placement builds both. Seek the opportunity.'",
                 "'Wait and see'",
                 "'Have a great holiday'"],
     "answerIndex": 1,
     "explanation": "A placement builds both evidence and vouching."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-j-B01", "type": "scored",
     "prompt": "What's the deck's headline about Skills Week?",
     "options": ["An optional week off",
                 "Your Work Experience week - the placement itself happens here",
                 "Only for Year 2 students",
                 "Cancelled this year"],
     "answerIndex": 1,
     "explanation": "This is your Work Experience week - the placement itself happens here."},
    {"id": "l3y1-j-B02", "type": "scored",
     "prompt": "Why does the deck say the request deadline is 4 weeks before Skills Week?",
     "options": ["Arbitrary",
                 "It gives the Careers & Employability team time to check your employer - health & safety, insurance and safeguarding checks - before you're allowed to start",
                 "To give students a deadline",
                 "Because employers are slow"],
     "answerIndex": 1,
     "explanation": "It gives the team time to check your employer - H&S, insurance, safeguarding."},
    {"id": "l3y1-j-B03", "type": "scored",
     "prompt": "Which room is the Eastbourne Careers & Employability team in?",
     "options": ["ECAT House, room 101", "Careers Hub, Ground Floor",
                 "Cliffe Building, room 134", "Ask at reception"],
     "answerIndex": 0,
     "explanation": "Eastbourne: ECAT House, room 101."},
    {"id": "l3y1-j-B04", "type": "insert",
     "prompt": "Fill in the blank: Lewes Careers & Employability is in the Cliffe Building, room ____.",
     "template": "Lewes Careers & Employability is in the Cliffe Building, room ____.",
     "options": ["12", "101", "134", "175"],
     "answerIndex": 2,
     "explanation": "Lewes: Cliffe Building, room 134."},
    {"id": "l3y1-j-B05", "type": "scored",
     "prompt": "What's the deck's view of the no-placement fallback?",
     "options": ["Skills Week is wasted",
                 "You'll come into college and work on an employer-set brief - a real task from a real employer - plus employer talks",
                 "You have to find one",
                 "It counts as a fail"],
     "answerIndex": 1,
     "explanation": "Employer-set brief in college - still counted, still worthwhile."},
    {"id": "l3y1-j-B06", "type": "scored",
     "prompt": "What does the deck say about dress code on placement?",
     "options": ["Always wear a suit",
                 "Check the dress code before you start; most studios, agencies and IT teams are smart casual; on a shoot or an install, wear something you can actually work in",
                 "Always wear your college uniform",
                 "It doesn't matter"],
     "answerIndex": 1,
     "explanation": "Smart casual - except on shoots or installs."},
    {"id": "l3y1-j-B07", "type": "scored",
     "prompt": "How does the deck reframe raising concerns on placement?",
     "options": ["Always wait until it gets worse",
                 "Speak to your employer contact first if it's minor; your tutor / Careers & Employability team if it isn't",
                 "Only escalate to the police",
                 "Don't raise them at all"],
     "answerIndex": 1,
     "explanation": "Employer contact first if minor; tutor/Careers if it isn't."},
    {"id": "l3y1-j-B08", "type": "multi",
     "prompt": "Which are options on the 'one thing' card? Select all that apply.",
     "options": ["Start looking - name one place I could approach this week",
                 "Note the dates - write 5 Feb and 8 March somewhere I'll see them",
                 "Get ready for Navigate - check I know what information I'll need",
                 "Tell someone - tell my tutor or Careers if unsure, or a placement concern comes up"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are options on the 'one thing' card."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-j-C01", "type": "scored",
     "prompt": "How long is the Module J session?",
     "options": ["About 30 minutes", "About 60 minutes", "About 90 minutes", "About 2 hours"],
     "answerIndex": 1,
     "explanation": "About 1 hour."},
    {"id": "l3y1-j-C02", "type": "scored",
     "prompt": "What does the deck say this industry hires on?",
     "options": ["Qualifications alone",
     "Evidence - a portfolio, a showreel, code you've written, a reference from someone who watched you work",
     "Connections",
     "Luck"],
     "answerIndex": 1,
     "explanation": "This industry hires on evidence."},
    {"id": "l3y1-j-C03", "type": "multi",
     "prompt": "Which of these count as work experience, according to the deck? Select all that apply.",
     "options": ["Block placement with one employer",
                 "Shorter, structured visits to a workplace",
                 "Unpaid work with a genuine organisational need",
                 "Real employer problems worked on in college"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "Block placement, employer visits, volunteering, and live project briefs are all on the list."},
    {"id": "l3y1-j-C04", "type": "scored",
     "prompt": "How long is a T Level industry placement?",
     "options": ["30 hours", "100 hours", "Around 315 hours", "1000 hours"],
     "answerIndex": 2,
     "explanation": "Around 315 hours."},
    {"id": "l3y1-j-C05", "type": "insert",
     "prompt": "Fill in the blank: the placement request deadline is Friday ____ February 2027.",
     "template": "The placement request deadline is Friday ____ February 2027.",
     "options": ["1st", "5th", "12th", "26th"],
     "answerIndex": 1,
     "explanation": "Friday 5 February 2027."},
    {"id": "l3y1-j-C06", "type": "scored",
     "prompt": "What does the deck say about Navigate's location?",
     "options": ["It's a separate app",
                 "Navigate lives inside My Student Life",
                 "It's on a USB stick",
                 "There's no app for this"],
     "answerIndex": 1,
     "explanation": "Navigate lives inside My Student Life."},
    {"id": "l3y1-j-C07", "type": "scored",
     "prompt": "What does the deck say about timekeeping?",
     "options": ["Be on time some days",
                 "Be on time, every day; running late or unwell? Contact the employer AND the college",
                 "Only turn up when you feel like it",
                 "Just call in if you're late"],
     "answerIndex": 1,
     "explanation": "Be on time, every day - and contact both the employer AND the college if running late or unwell."},
    {"id": "l3y1-j-C08", "type": "scored",
     "prompt": "What's the deck's framing of the placement as a whole?",
     "options": ["'It's a box-ticking exercise'",
                 "'In this industry you are hired on what you can show and who will vouch for you - a placement builds both. Seek the opportunity.'",
                 "'It's optional'",
                 "'It's only useful if paid'"],
     "answerIndex": 1,
     "explanation": "Seek the opportunity."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-j-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")