#!/usr/bin/env python3
"""Quizzes A/B/C for Module I L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-i",
    "level": "l3",
    "year": "y1",
    "module": "I",
    "title": "Professional Behaviour & Personal Strengths",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-i-A01", "type": "scored",
     "prompt": "Which PROUD value is this module grounded in?",
     "options": ["Seek Opportunity", "Show Respect", "Encourage Unity", "Be Proud"],
     "answerIndex": 1,
     "explanation": "Show Respect."},
    {"id": "l3y1-i-A02", "type": "scored",
     "prompt": "What's the deck's framing of professionalism?",
     "options": ["A costume for interviews",
                 "A set of habits - and the habits don't change with the setting",
                 "Something only relevant in employment",
                 "Only required on placement"],
     "answerIndex": 1,
     "explanation": "Professionalism isn't a costume - it's a set of habits that don't change with the setting."},
    {"id": "l3y1-i-A03", "type": "multi",
     "prompt": "Which of these are the four professional habits the deck lists? Select all that apply.",
     "options": ["Turning up - on time, kit charged, files backed up",
                 "Flagging problems early",
                 "How you speak to people - in the room, in the group chat, and online",
                 "Owning mistakes and putting them right"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are the professional habits - same across college, placement, and employment."},
    {"id": "l3y1-i-A04", "type": "scored",
     "prompt": "What does the deck say matters for your reference?",
     "options": ["A single bad day",
                 "The pattern across the year - which is the one thing you fully control",
                 "Your tutor's mood",
                 "Your predicted grade"],
     "answerIndex": 1,
     "explanation": "One rough week doesn't follow you. A pattern does - and that's the one thing you fully control."},
    {"id": "l3y1-i-A05", "type": "insert",
     "prompt": "Fill in the blank: at entry level, the deciding factors are ____.",
     "template": "At entry level, the deciding factors are ____.",
     "options": ["technical", "human", "academic", "creative"],
     "answerIndex": 1,
     "explanation": "At entry level, employers consistently report that the deciding factors are human."},
    {"id": "l3y1-i-A06", "type": "scored",
     "prompt": "Which of these is one of the six human skills in the deck?",
     "options": ["Compliance", "Initiative", "Volume", "Tenacity"],
     "answerIndex": 1,
     "explanation": "Initiative: spotting what needs doing without being asked."},
    {"id": "l3y1-i-A07", "type": "scored",
     "prompt": "Which version of a strength statement lands as evidence?",
     "options": ["'I'm a good team player'",
                 "'On our last project I chaired the planning and set the deadlines - everyone knew their job, and we submitted on time'",
                 "'I'm confident'",
                 "'I'm hard-working'"],
     "answerIndex": 1,
     "explanation": "Specific, checkable, memorable."},
    {"id": "l3y1-i-A08", "type": "scored",
     "prompt": "What does the deck say if you can't find three strengths?",
     "options": ["Drop out",
                 "You're not short of strengths - you're short of practice noticing them",
                 "Switch course",
                 "Use claims instead"],
     "answerIndex": 1,
     "explanation": "You're not short of strengths - you're short of practice noticing them."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-i-B01", "type": "scored",
     "prompt": "What does the deck say about 'soft' skills?",
     "options": ["They're soft",
                 "There's nothing soft about being the person a team relies on - and they're the skills that don't automate",
                 "They're optional",
                 "They're for non-creative work only"],
     "answerIndex": 1,
     "explanation": "There's nothing soft about being the person a team relies on."},
    {"id": "l3y1-i-B02", "type": "scored",
     "prompt": "How does the deck frame the Skills Assessment?",
     "options": ["A verdict",
                 "A starting point, not a verdict - it gives you language and a place to begin; the judgement stays yours",
                 "An exam",
                 "A pass/fail test"],
     "answerIndex": 1,
     "explanation": "The assessment is a starting point, not a verdict. The judgement stays yours."},
    {"id": "l3y1-i-B03", "type": "scored",
     "prompt": "What's the formula the deck gives for writing an evidenced strength statement?",
     "options": ["Claim -> repeat -> claim",
                 "Situation -> what you actually do -> what it shows",
                 "Story -> lesson -> moral"],
     "answerIndex": 1,
     "explanation": "Situation -> what you actually do -> what it shows."},
    {"id": "l3y1-i-B04", "type": "multi",
     "prompt": "Which of these count as evidence, according to the deck? Select all that apply.",
     "options": ["Projects and placement", "Part-time jobs",
                 "Caring for someone", "Sport"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "Evidence doesn't have to be paid work - projects, placement, part-time jobs, caring for someone, sport - it all counts."},
    {"id": "l3y1-i-B05", "type": "scored",
     "prompt": "How should you choose which three strengths to draft?",
     "options": ["The ones that sound best",
                 "The three with the strongest evidence behind them - not the three that sound best",
                 "The ones your friends like",
                 "The ones you've never mentioned before"],
     "answerIndex": 1,
     "explanation": "Pick the three with the strongest evidence behind them."},
    {"id": "l3y1-i-B06", "type": "scored",
     "prompt": "What does the deck say is the partner's job when testing strength statements?",
     "options": ["To approve them",
                 "To ask 'what's your evidence?' until they believe you",
                 "To write them for you",
                 "To rank them"],
     "answerIndex": 1,
     "explanation": "Their only job is to ask 'what's your evidence?' until they believe you."},
    {"id": "l3y1-i-B07", "type": "multi",
     "prompt": "Which of these are options on the 'one thing' card? Select all that apply.",
     "options": ["Act on my Skills Assessment development priority - one concrete step, named",
                 "Use one of my three strength statements somewhere real",
                 "Practise one professional habit deliberately for the week",
                 "Tell someone about something that's making it hard to show up"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are options on the 'one thing' card."},
    {"id": "l3y1-i-B08", "type": "scored",
     "prompt": "What's the deck's closing line?",
     "options": ["'Get good marks'",
                 "'One standard, three contexts - it's the same tomorrow as it was today. That's the whole point.'",
                 "'Wait until Year 2'",
                 "'Focus on the grade'"],
     "answerIndex": 1,
     "explanation": "The standard doesn't reset."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-i-C01", "type": "scored",
     "prompt": "How long is the Module I session?",
     "options": ["About 30 minutes", "About 60 minutes", "90 minutes", "About 2 hours"],
     "answerIndex": 2,
     "explanation": "Module I is 90 minutes."},
    {"id": "l3y1-i-C02", "type": "scored",
     "prompt": "What's the headline of the module?",
     "options": ["'Get a job'",
                 "'One standard - in college, on placement, in employment'",
                 "'Pass your exams'",
                 "'Build a portfolio'"],
     "answerIndex": 1,
     "explanation": "One standard - in college, on placement, in employment."},
    {"id": "l3y1-i-C03", "type": "scored",
     "prompt": "Which of these is NOT one of the six human skills in the deck?",
     "options": ["Communication", "Reliability", "Compliance", "Initiative"],
     "answerIndex": 2,
     "explanation": "Compliance is not listed. The six are Communication, Teamwork, Reliability, Problem-solving, Adaptability, Initiative."},
    {"id": "l3y1-i-C04", "type": "insert",
     "prompt": "Fill in the blank: the Skills Assessment cross-check step asks whether a partner's read matches the ____.",
     "template": "The Skills Assessment cross-check step asks whether a partner's read matches the ____.",
     "options": ["tutor's view", "assessment's view", "parent's view", "grade"],
     "answerIndex": 1,
     "explanation": "Does their read of you match the assessment's?"},
    {"id": "l3y1-i-C05", "type": "scored",
     "prompt": "What's the deck's view on evidence sources?",
     "options": ["Only paid work counts",
                 "Evidence doesn't have to be paid work - projects, placement, part-time jobs, caring for someone, sport, anything you've made or run - it all counts",
                 "Only award-winning work counts",
                 "Only work in the industry counts"],
     "answerIndex": 1,
     "explanation": "It all counts."},
    {"id": "l3y1-i-C06", "type": "scored",
     "prompt": "What's the deck's framing of 'I'm a good team player'?",
     "options": ["A great strength statement",
                 "A claim - it costs nothing and proves nothing; interviewers hear it forty times a week",
                 "The right answer",
                 "An evidence statement"],
     "answerIndex": 1,
     "explanation": "A claim - interviewers hear it forty times a week."},
    {"id": "l3y1-i-C07", "type": "scored",
     "prompt": "What does the deck say the three strengths feed into?",
     "options": ["A job application",
                 "Your Digital CV, your placement applications and everything else you apply for",
                 "Your tutor's notes",
                 "Your attendance record"],
     "answerIndex": 1,
     "explanation": "They'll feed your Digital CV, your placement applications and everything else you apply for."},
    {"id": "l3y1-i-C08", "type": "scored",
     "prompt": "What's the closing line of Module I?",
     "options": ["'Good luck'",
                 "'One standard, three contexts - it's the same tomorrow as it was today. That's the whole point.'",
                 "'See you next term'",
                 "'Practice makes perfect'"],
     "answerIndex": 1,
     "explanation": "The standard doesn't reset."}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-i-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")