#!/usr/bin/env python3
"""Quizzes A/B/C for Module E L3 Y1."""
import json
from pathlib import Path

META = {
    "section": "l3y1-e",
    "level": "l3",
    "year": "y1",
    "module": "E",
    "title": "Respect, Relationships & College Values",
}

quiz_a = {"meta": {**META, "variant": "A"}, "questions": [
    {"id": "l3y1-e-A01", "type": "scored",
     "prompt": "Which PROUD value means 'include others; challenge exclusion; work positively across difference'?",
     "options": ["Bring Positivity", "Show Respect", "Encourage Unity", "Celebrate Diversity"],
     "answerIndex": 2,
     "explanation": "Encourage Unity: include others; challenge exclusion; work positively across difference."},
    {"id": "l3y1-e-A02", "type": "multi",
     "prompt": "Which of these are PROUD values? Select all that apply.",
     "options": ["Bring Positivity", "Show Respect", "Seek Opportunity", "Encourage Unity", "Celebrate Diversity"],
     "correctIndices": [0, 1, 2, 3, 4],
     "explanation": "All five are PROUD values."},
    {"id": "l3y1-e-A03", "type": "scored",
     "prompt": "Which British Value says your voice matters through elections, surveys and governance?",
     "options": ["Rule of Law", "Democracy", "Individual Liberty", "Mutual Respect & Tolerance"],
     "answerIndex": 1,
     "explanation": "Democracy."},
    {"id": "l3y1-e-A04", "type": "insert",
     "prompt": "Fill in the blank: the Equality Act 2010 lists ____ protected characteristics.",
     "template": "The Equality Act 2010 lists ____ protected characteristics.",
     "options": ["3", "5", "7", "9"],
     "answerIndex": 3,
     "explanation": "9 protected characteristics."},
    {"id": "l3y1-e-A05", "type": "scored",
     "prompt": "According to the deck, what does the Equality Act describe as 'unwanted behaviour that violates dignity or creates a hostile, humiliating or offensive environment'?",
     "options": ["Discrimination", "Harassment", "Victimisation", "Bullying"],
     "answerIndex": 1,
     "explanation": "Harassment is unwanted behaviour that violates dignity or creates a hostile, humiliating or offensive environment."},
    {"id": "l3y1-e-A06", "type": "scored",
     "prompt": "Where do Behaviour Standards apply, according to the deck?",
     "options": ["Only in college", "Only on placement", "In college, on placement, and online", "Only in lessons"],
     "answerIndex": 2,
     "explanation": "The same standard applies - in college, on placement, and online."},
    {"id": "l3y1-e-A07", "type": "multi",
     "prompt": "Which of these are covered by ESCG's Zero Tolerance position? Select all that apply.",
     "options": ["Harassment", "Discrimination", "Bullying", "Abuse - including online abuse directed at college members"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are covered by zero tolerance."},
    {"id": "l3y1-e-A08", "type": "scored",
     "prompt": "What does the deck say about anonymous reports?",
     "options": ["They are ignored",
                 "They are only investigated if you give your name",
                 "They are still investigated - you don't have to identify yourself to be heard",
                 "They must be made in writing"],
     "answerIndex": 2,
     "explanation": "Anonymous reports are still investigated - you don't have to identify yourself to be heard."}
]}

quiz_b = {"meta": {**META, "variant": "B"}, "questions": [
    {"id": "l3y1-e-B01", "type": "dragorder",
     "prompt": "Put the five PROUD values in the order the deck presents them.",
     "items": ["Bring Positivity", "Show Respect", "Seek Opportunity", "Encourage Unity", "Celebrate Diversity"],
     "solution": [0, 1, 2, 3, 4],
     "explanation": "The five values are presented in the order P-R-O-U-D."},
    {"id": "l3y1-e-B02", "type": "scored",
     "prompt": "Which British Value says breaches 'may have disciplinary or legal consequences'?",
     "options": ["Democracy", "Rule of Law", "Individual Liberty", "Mutual Respect & Tolerance"],
     "answerIndex": 1,
     "explanation": "Rule of Law - breaches may have disciplinary or legal consequences."},
    {"id": "l3y1-e-B03", "type": "multi",
     "prompt": "Which of these are protected characteristics under the Equality Act 2010? Select all that apply.",
     "options": ["Race", "Religion or belief", "Sexual orientation", "Being a student rep"],
     "correctIndices": [0, 1, 2],
     "explanation": "Race, religion or belief, and sexual orientation are three of the nine protected characteristics. Being a student rep is not."},
    {"id": "l3y1-e-B04", "type": "scored",
     "prompt": "How does the deck define victimisation under the Equality Act?",
     "options": ["Treating someone less favourably because of a protected characteristic",
                 "Unwanted behaviour that violates dignity",
                 "Treating someone unfairly because they raised - or supported - a discrimination concern",
                 "Repeated behaviour intended to intimidate, control, or harm"],
     "answerIndex": 2,
     "explanation": "Victimisation is treating someone unfairly because they raised - or supported - a discrimination concern."},
    {"id": "l3y1-e-B05", "type": "scored",
     "prompt": "On placement, who should you report concerns to, according to the deck?",
     "options": ["Just the placement provider",
                 "No one - it's not your job",
                 "Your teacher - not just the placement provider",
                 "Only the HR department"],
     "answerIndex": 2,
     "explanation": "Report concerns to your teacher, not just the placement provider."},
    {"id": "l3y1-e-B06", "type": "scored",
     "prompt": "What's the deck's view of content posted outside college?",
     "options": ["It can't affect you at college",
                 "It can still lead to disciplinary action",
                 "Only if it's posted during term time",
                 "Only if it's tagged with the college"],
     "answerIndex": 1,
     "explanation": "Content posted outside college can still lead to disciplinary action."},
    {"id": "l3y1-e-B07", "type": "multi",
     "prompt": "Which of these are routes for reporting a concern, according to the deck? Select all that apply.",
     "options": ["Tell your teacher", "Formal reporting system", "Anonymous reporting", "Posting on social media"],
     "correctIndices": [0, 1, 2],
     "explanation": "Tell your teacher, formal reporting system, and anonymous reporting are the three routes."},
    {"id": "l3y1-e-B08", "type": "multi",
     "prompt": "Which of these are 'I will challenge...' options on the commitment card? Select all that apply.",
     "options": ["A joke or comment that targets someone's identity - even if it's meant to be funny",
                 "A situation where someone is being left out or excluded",
                 "Behaviour online that I'd find unacceptable face-to-face",
                 "My own assumptions about people who are different from me"],
     "correctIndices": [0, 1, 2, 3],
     "explanation": "All four are 'I will challenge...' options."}
]}

quiz_c = {"meta": {**META, "variant": "C"}, "questions": [
    {"id": "l3y1-e-C01", "type": "scored",
     "prompt": "Which PROUD value means 'create a welcoming environment where everyone feels safe and included'?",
     "options": ["Bring Positivity", "Show Respect", "Seek Opportunity", "Celebrate Diversity"],
     "answerIndex": 0,
     "explanation": "Bring Positivity: create a welcoming environment where everyone feels safe and included."},
    {"id": "l3y1-e-C02", "type": "scored",
     "prompt": "Which British Value covers making informed choices about your beliefs, lifestyle, and identity - as long as it doesn't restrict or harm others?",
     "options": ["Democracy", "Rule of Law", "Individual Liberty", "Mutual Respect & Tolerance"],
     "answerIndex": 2,
     "explanation": "Individual Liberty - informed choices about beliefs, lifestyle, and identity."},
    {"id": "l3y1-e-C03", "type": "scored",
     "prompt": "Which Equality Act term means 'treating someone unfairly because of a protected characteristic'?",
     "options": ["Discrimination", "Harassment", "Victimisation", "Bullying"],
     "answerIndex": 0,
     "explanation": "Discrimination is treating someone unfairly because of a protected characteristic."},
    {"id": "l3y1-e-C04", "type": "scored",
     "prompt": "Which PROUD value says 'our differences strengthen the college; value every person for who they are'?",
     "options": ["Bring Positivity", "Show Respect", "Encourage Unity", "Celebrate Diversity"],
     "answerIndex": 3,
     "explanation": "Celebrate Diversity - our differences strengthen the college."},
    {"id": "l3y1-e-C05", "type": "multi",
     "prompt": "In the 'In College' Behaviour Standards, which of these apply? Select all that apply.",
     "options": ["Respectful language and conduct toward all students and staff",
                 "No bullying, harassment, or discriminatory behaviour",
                 "Personal devices used responsibly - not to film or record without consent",
                 "Sharing placement footage in the college group chat without checking"],
     "correctIndices": [0, 1, 2],
     "explanation": "Respectful language, no bullying/harassment/discrimination, and responsible device use are the In College standards."},
    {"id": "l3y1-e-C06", "type": "insert",
     "prompt": "Fill in the blank: ESCG's position on harassment, discrimination, bullying and abuse is 'not a preference, not a guideline' - it's __.",
     "template": "ESCG's position on harassment, discrimination, bullying and abuse is 'not a preference, not a guideline' - it's __.",
     "options": ["optional", "discretionary", "zero tolerance", "case-by-case"],
     "answerIndex": 2,
     "explanation": "Zero tolerance - 'not a preference, not a guideline'."},
    {"id": "l3y1-e-C07", "type": "scored",
     "prompt": "Which phrase from the deck captures the Equality Act quote?",
     "options": ["'Living the Equality Act is optional.'",
                 "'Living the PROUD values is living the Equality Act in practice.'",
                 "'PROUD values override the Equality Act.'",
                 "'The Equality Act is for staff only.'"],
     "answerIndex": 1,
     "explanation": "'Living the PROUD values = living the Equality Act in practice.'"},
    {"id": "l3y1-e-C08", "type": "scored",
     "prompt": "What's the deck's headline line about reporting?",
     "options": ["You always have options - and you will always be taken seriously",
                 "Reporting is discouraged",
                 "Only formal reports are accepted",
                 "Only named reports are investigated"],
     "answerIndex": 0,
     "explanation": "'You always have options - and you will always be taken seriously.'"}
]}

base = Path("data")
for v, q in [("A", quiz_a), ("B", quiz_b), ("C", quiz_c)]:
    p = base / f"l3y1-e-quiz-{v}.json"
    p.write_text(json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {p}")