const CACHE_NAME = 'induction-quiz-v15';

const APP_SHELL = [
  './',
  './index.html',
  './styles.css',
  './js/app.js',
  './js/storage.js',
  './js/helpers.js',
  './js/settings.js',
  './js/learn.js',
  './js/quiz.js',
  './js/results.js',
  './js/progress.js',
  './js/firebase-config.js',
  './js/databaseManager.js',
  './js/classroom.js',
  './manifest.webmanifest',
  './favicon.svg',
  './logo.svg',
  './apple-touch-icon.png',
  './web-app-manifest-192x192.png',
  './web-app-manifest-512x512.png',
  './favicon-96x96.png',
  './data/y1a/l3y1-a-learn.json',
  './data/y1a/l3y1-a-quiz-A.json',
  './data/y1a/l3y1-a-quiz-B.json',
  './data/y1a/l3y1-a-quiz-C.json',
  './data/y1a/l3y1-b-learn.json',
  './data/y1a/l3y1-b-quiz-A.json',
  './data/y1a/l3y1-b-quiz-B.json',
  './data/y1a/l3y1-b-quiz-C.json',
  './data/y1a/l3y1-c-learn.json',
  './data/y1a/l3y1-c-quiz-A.json',
  './data/y1a/l3y1-c-quiz-B.json',
  './data/y1a/l3y1-c-quiz-C.json',
  './data/y1a/l3y1-d-learn.json',
  './data/y1a/l3y1-d-quiz-A.json',
  './data/y1a/l3y1-d-quiz-B.json',
  './data/y1a/l3y1-d-quiz-C.json',
  './data/y1a/l3y1-e-learn.json',
  './data/y1a/l3y1-e-quiz-A.json',
  './data/y1a/l3y1-e-quiz-B.json',
  './data/y1a/l3y1-e-quiz-C.json',
  './data/y1a/l3y1-f-learn.json',
  './data/y1a/l3y1-f-quiz-A.json',
  './data/y1a/l3y1-f-quiz-B.json',
  './data/y1a/l3y1-f-quiz-C.json',
  './data/y1a/l3y1-g-learn.json',
  './data/y1a/l3y1-g-quiz-A.json',
  './data/y1a/l3y1-g-quiz-B.json',
  './data/y1a/l3y1-g-quiz-C.json',
  './data/y1a/l3y1-h-learn.json',
  './data/y1a/l3y1-h-quiz-A.json',
  './data/y1a/l3y1-h-quiz-B.json',
  './data/y1a/l3y1-h-quiz-C.json',
  './data/y1a/l3y1-i-learn.json',
  './data/y1a/l3y1-i-quiz-A.json',
  './data/y1a/l3y1-i-quiz-B.json',
  './data/y1a/l3y1-i-quiz-C.json',
  './data/y1a/l3y1-j-learn.json',
  './data/y1a/l3y1-j-quiz-A.json',
  './data/y1a/l3y1-j-quiz-B.json',
  './data/y1a/l3y1-j-quiz-C.json',
  './data/y1a/l3y1-k-learn.json',
  './data/y1a/l3y1-k-quiz-A.json',
  './data/y1a/l3y1-k-quiz-B.json',
  './data/y1a/l3y1-k-quiz-C.json',
  './data/y1b/l3y1-a-learn.json',
  './data/y1b/l3y1-a-quiz-A.json',
  './data/y1b/l3y1-a-quiz-B.json',
  './data/y1b/l3y1-a-quiz-C.json',
  './data/y1b/l3y1-b-learn.json',
  './data/y1b/l3y1-b-quiz-A.json',
  './data/y1b/l3y1-b-quiz-B.json',
  './data/y1b/l3y1-b-quiz-C.json',
  './data/y1b/l3y1-c-learn.json',
  './data/y1b/l3y1-c-quiz-A.json',
  './data/y1b/l3y1-c-quiz-B.json',
  './data/y1b/l3y1-c-quiz-C.json',
  './data/y1b/l3y1-d-learn.json',
  './data/y1b/l3y1-d-quiz-A.json',
  './data/y1b/l3y1-d-quiz-B.json',
  './data/y1b/l3y1-d-quiz-C.json',
  './data/y1b/l3y1-e-learn.json',
  './data/y1b/l3y1-e-quiz-A.json',
  './data/y1b/l3y1-e-quiz-B.json',
  './data/y1b/l3y1-e-quiz-C.json',
  './data/y1b/l3y1-f-learn.json',
  './data/y1b/l3y1-f-quiz-A.json',
  './data/y1b/l3y1-f-quiz-B.json',
  './data/y1b/l3y1-f-quiz-C.json',
  './data/y1b/l3y1-g-learn.json',
  './data/y1b/l3y1-g-quiz-A.json',
  './data/y1b/l3y1-g-quiz-B.json',
  './data/y1b/l3y1-g-quiz-C.json',
  './data/y1b/l3y1-h-learn.json',
  './data/y1b/l3y1-h-quiz-A.json',
  './data/y1b/l3y1-h-quiz-B.json',
  './data/y1b/l3y1-h-quiz-C.json',
  './data/y1b/l3y1-i-learn.json',
  './data/y1b/l3y1-i-quiz-A.json',
  './data/y1b/l3y1-i-quiz-B.json',
  './data/y1b/l3y1-i-quiz-C.json',
  './data/y1b/l3y1-j-learn.json',
  './data/y1b/l3y1-j-quiz-A.json',
  './data/y1b/l3y1-j-quiz-B.json',
  './data/y1b/l3y1-j-quiz-C.json',
  './data/y1b/l3y1-k-learn.json',
  './data/y1b/l3y1-k-quiz-A.json',
  './data/y1b/l3y1-k-quiz-B.json',
  './data/y1b/l3y1-k-quiz-C.json',
  './data/y2a/l3y2-a-learn.json',
  './data/y2a/l3y2-a-quiz-A.json',
  './data/y2a/l3y2-a-quiz-B.json',
  './data/y2a/l3y2-a-quiz-C.json',
  './data/y2a/l3y2-b-learn.json',
  './data/y2a/l3y2-b-quiz-A.json',
  './data/y2a/l3y2-b-quiz-B.json',
  './data/y2a/l3y2-b-quiz-C.json',
  './data/y2a/l3y2-c-learn.json',
  './data/y2a/l3y2-c-quiz-A.json',
  './data/y2a/l3y2-c-quiz-B.json',
  './data/y2a/l3y2-c-quiz-C.json',
  './data/y2a/l3y2-d-learn.json',
  './data/y2a/l3y2-d-quiz-A.json',
  './data/y2a/l3y2-d-quiz-B.json',
  './data/y2a/l3y2-d-quiz-C.json',
  './data/y2a/l3y2-e-learn.json',
  './data/y2a/l3y2-e-quiz-A.json',
  './data/y2a/l3y2-e-quiz-B.json',
  './data/y2a/l3y2-e-quiz-C.json',
  './data/y2a/l3y2-f-learn.json',
  './data/y2a/l3y2-f-quiz-A.json',
  './data/y2a/l3y2-f-quiz-B.json',
  './data/y2a/l3y2-f-quiz-C.json',
  './data/y2a/l3y2-g-learn.json',
  './data/y2a/l3y2-g-quiz-A.json',
  './data/y2a/l3y2-g-quiz-B.json',
  './data/y2a/l3y2-g-quiz-C.json',
  './data/y2a/l3y2-h-learn.json',
  './data/y2a/l3y2-h-quiz-A.json',
  './data/y2a/l3y2-h-quiz-B.json',
  './data/y2a/l3y2-h-quiz-C.json',
  './data/y2a/l3y2-i-learn.json',
  './data/y2a/l3y2-i-quiz-A.json',
  './data/y2a/l3y2-i-quiz-B.json',
  './data/y2a/l3y2-i-quiz-C.json',
  './data/y2a/l3y2-j-learn.json',
  './data/y2a/l3y2-j-quiz-A.json',
  './data/y2a/l3y2-j-quiz-B.json',
  './data/y2a/l3y2-j-quiz-C.json',
  './data/y2a/l3y2-k-learn.json',
  './data/y2a/l3y2-k-quiz-A.json',
  './data/y2a/l3y2-k-quiz-B.json',
  './data/y2a/l3y2-k-quiz-C.json',
  './data/y2b/l3y2-a-learn.json',
  './data/y2b/l3y2-a-quiz-A.json',
  './data/y2b/l3y2-a-quiz-B.json',
  './data/y2b/l3y2-a-quiz-C.json',
  './data/y2b/l3y2-b-learn.json',
  './data/y2b/l3y2-b-quiz-A.json',
  './data/y2b/l3y2-b-quiz-B.json',
  './data/y2b/l3y2-b-quiz-C.json',
  './data/y2b/l3y2-c-learn.json',
  './data/y2b/l3y2-c-quiz-A.json',
  './data/y2b/l3y2-c-quiz-B.json',
  './data/y2b/l3y2-c-quiz-C.json',
  './data/y2b/l3y2-d-learn.json',
  './data/y2b/l3y2-d-quiz-A.json',
  './data/y2b/l3y2-d-quiz-B.json',
  './data/y2b/l3y2-d-quiz-C.json',
  './data/y2b/l3y2-e-learn.json',
  './data/y2b/l3y2-e-quiz-A.json',
  './data/y2b/l3y2-e-quiz-B.json',
  './data/y2b/l3y2-e-quiz-C.json',
  './data/y2b/l3y2-f-learn.json',
  './data/y2b/l3y2-f-quiz-A.json',
  './data/y2b/l3y2-f-quiz-B.json',
  './data/y2b/l3y2-f-quiz-C.json',
  './data/y2b/l3y2-g-learn.json',
  './data/y2b/l3y2-g-quiz-A.json',
  './data/y2b/l3y2-g-quiz-B.json',
  './data/y2b/l3y2-g-quiz-C.json',
  './data/y2b/l3y2-h-learn.json',
  './data/y2b/l3y2-h-quiz-A.json',
  './data/y2b/l3y2-h-quiz-B.json',
  './data/y2b/l3y2-h-quiz-C.json',
  './data/y2b/l3y2-i-learn.json',
  './data/y2b/l3y2-i-quiz-A.json',
  './data/y2b/l3y2-i-quiz-B.json',
  './data/y2b/l3y2-i-quiz-C.json',
  './data/y2b/l3y2-j-learn.json',
  './data/y2b/l3y2-j-quiz-A.json',
  './data/y2b/l3y2-j-quiz-B.json',
  './data/y2b/l3y2-j-quiz-C.json',
  './data/y2b/l3y2-k-learn.json',
  './data/y2b/l3y2-k-quiz-A.json',
  './data/y2b/l3y2-k-quiz-B.json',
  './data/y2b/l3y2-k-quiz-C.json',
  './gfx/logo_black.png',
  './gfx/logo_black.svg',
  './gfx/logo_white.png',
  './gfx/logo_white.svg',
  './sfx/ping_pong.mp3',
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return Promise.all(APP_SHELL.map(function (url) {
        return fetch(url, { cache: 'no-cache' }).then(function (response) {
          if (response && response.status === 200) return cache.put(url, response);
          return null;
        }).catch(function () {
          return null;
        });
      }));
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE_NAME; }).map(function (k) { return caches.delete(k); }));
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', function (event) {
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      if (cached) return cached;
      return fetch(event.request).then(function (response) {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then(function (cache) {
            cache.put(event.request, clone);
          });
        }
        return response;
      }).catch(function () {
        return caches.match('./index.html');
      });
    })
  );
});
